### PR TITLE
Fix for Multicast to level 4

### PR DESCRIPTION
**Pull request by TMRh20**
https://github.com/nRF24/RF24Network/issues/226
- Define NETWORK_MULTICAST_ADDRESS_LEVEL_2 and NETWORK_MULTICAST_ADDRESS_LEVEL_4 in RF24Network.cpp
- Add the above to valid addresses in `is_valid_address();`

### CODE REVIEW

**Comment by 2bndy5** [comment]
Does net level 3 not have any problems? Or are we only compensating for known/reported problems?

**Comment by TMRh20** [comment]
Hmm, this library IS a bit confusing. Level 3 is 0100 or the default NETWORK_MULTICAST_ADDRESS, so it is accounted for. The only thing I'm curious about is potential conflicts between multicast address level 1 (01) and assigned address at RF24Network address 01 as they are the same digit... I haven't had a chance to look into it at all.

**Comment by 2bndy5** [comment]
Oh right. I was confusing 04444 with NETWORK_MULTICAST_ADDRESS. Obviously, its been a while since I actually looked at the code in depth.

As for the 01 conflict, we could use a reserved bit in the header to distinguish between multicast or direct writes.

**Comment by TMRh20** [comment]
> As for the 01 conflict, we could use a reserved bit in the header to distinguish between multicast or direct writes.

Is it needed? I don't quite know yet. I also thought about just changing the multicast level addresses to 06... or 07, 070, 0700, 07000

**Review by 2bndy5 — APPROVED** [review]

**Pull request merged**
